version: '2'

services:
  apirunner:
    image: lykkedev/rabbitforward:dev
    ports:
     - "80:4666"
    environment:
     - SettingsUrl=https://settings-dev.lykkex.net/cdcsdfaregegffds_LykkePayServiceWallet